# ?? ?? ??? ???
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ?? DB? ????? ??
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: debug
