# ?? ?? ??? ???
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ?? DB? ????? ??
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: debug

# Firebase ? ?? ?? ?? (???)
firebase:
  key-path: classpath:firebase-service-account-key.json

gemini:
  api-key: ${GOOGLE_API_KEY}

server:
  address: 0.0.0.0
  port: 8080